### ISSUE TITLE
[Very minor] dzil error when following contributing instructions: "[DZ] no version was ever set"

### ISSUE THREAD

**Issue by mjemmeson** [dagolden/File-chdir#5]
Hi,

File::chdir has no VERSION set, and so as such the contributing instructions are wrong for building the module, giving the error "no version was ever set"

I suppose the fix is either to add the VERSION to the module or to update the CONTRIBUTING file to state something like:

    V=x.xx dzil build 

thanks,
Michael

**Comment by dagolden** [comment]
Thanks for the report.  I've updated my dzil bundle and haven't yet fixed up my hundred or so repositories.  I'll get that done for File-chdir right now.

**Comment by mjemmeson** [comment]
Thanks! Further question, what is the ':version' line about? It's not documented in your pluginbundle docs and couldn't see it mentioned in any of the version related plugins used

**Comment by dagolden** [comment]
The `:version` line in dist.ini is a meta-instruction to tell Dist::Zilla to require a minimum version of a particular plugin or pluginbundle.  It's just dzil arcana.  Sorry about that.
