### ISSUE TITLE
File::chdir docs

### ISSUE THREAD

**Issue by SpoofMutt** [dagolden/File-chdir#8]
Okay, if you were being humorous then I guess it was too subtle for me. :) However, you're text says, "Was it over when the Germans bombed Pearl Harbor?". Seeing how Germany has never bombed Pearl Harbor - yet - I assume you meant Japan. No?

**Comment by xdg** [comment]
It's a reference to the movie Animal House.  https://www.youtube.com/watch?v=V8lT1o0sDwI

When I took over maintenance, I didn't clean up the humor.
